services:
  - type: web
    name: facilita-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MINHA_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: OPENROUTER_KEY
        sync: false
      - key: DB_PATH
        value: /opt/render/project/src/crm_facilita.db
      - key: SERP_LL
        value: "@-23.5505,-46.6333,20z"
      - key: OPENROUTER_MODEL
        value: deepseek/deepseek-r1-0528:free
